name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v4
    - run: uv python install 3.11
    - run: uv sync --group dev
    - run: uv run ruff check src/ tests/
    - run: uv run ruff format --check src/ tests/
    - run: uv run pyright src/

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v4
    - run: uv python install ${{ matrix.python-version }}
    - run: uv sync --group dev
    - run: uv run pytest tests/ -v --cov=src
